language: go

go:
  - master
  - tip

install:
  - go get -t ./...
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/staticcheck
  - go get github.com/kisielk/errcheck

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - misspell -error .
  - go vet ./...
  - go test -v -tags=integration ./...

after_script:
  - golint ./...
  - staticcheck ./...
  - errcheck ./...
